spring:
  cloud:
    gateway:
      routes:
        - id: first-api-example
          uri: http://localhost:8081/
          predicates:
            - Path=/request
          filters:
            - SetPath=/example-api
           